services:
  redis:
    image: redis:alpine
    container_name: car-repair-redis-dev
    ports:
      - "6379:6379"
    networks:
      - redis_network

  mysql:
    image: mysql:8.0.36-debian
    container_name: car-repair-mysql-dev
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: car-repair
    ports:
      - "3306:3306"
    networks:
      - mysql_network
    volumes:
      - mysql-dev-data:/var/lib/mysql
      - ./mySqlInit.sql:/docker-entrypoint-initdb.d/mySqlInit.sql

volumes:
  mysql-dev-data:
    driver: local

networks:
  redis_network:
  mysql_network:
