# Development specific configuration (activated when 'dev' profile is active)
spring:
  data:
    redis:
      host: redis
      port: 6379
  datasource:
    url: jdbc:mysql://mysql:3306/car-repair
    username: root
    password: password

  # --- Dev JPA/Hibernate Settings ---
  jpa:
    show-sql: true
    open-in-view: true

  # --- Dev Docker Compose Integration ---
  docker:
    compose:
      lifecycle-management: start_only
      enabled: true

  # --- Dev Springdoc / Swagger UI ---
springdoc:
  api-docs:
    enabled: true  # Indented under api-docs
  swagger-ui:
    enabled: true  # Indented under swagger-ui

# --- Dev Logging ---
logging:
  level:
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: error
    org:
      springframework:
        web: DEBUG
        security: DEBUG
      hibernate:
        SQL: DEBUG

  file:
    name: logs/autorepair-dev.log

openapi:
  server:
    url: http://192.168.1.2:8080

JWT_SECRET_KEY: HEVSvTQ21+BIvaeTQBlV5LVFSczW9QGLp3QgikovoGI=
isHttpsEnabled : false