spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${db_user}
    password: ${db_password}

  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  docker:
    compose:
      lifecycle-management: start_only
      enabled: ${DOCKER_COMPOSE_ENABLED:false}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: error
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
  file:
    name: logs/autorepair-dev.log

server:
  port: 8080
  ssl:
    enabled: ${isHttpsEnabled:false}
    certificate: classpath:localhost.pem
    certificate-private-key: classpath:localhost-key.pem

# --- Actuator Configuration ---
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

# --- Custom Variables ---
openapi:
  server:
    url: http://localhost:8080/

JWT_SECRET_KEY: ${JWT_SECRET:HEVSvTQ21+BIvaeTQBlV5LVFSczW9QGLp3QgikovoGI=}
isHttpsEnabled: false

frontend: ${frontend-net:http://localhost}
