spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:car-repair}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validat
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  docker:
    compose:
      enabled: false

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

logging:
  level:
    root: INFO
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: error

JWT_SECRET_KEY: ${JWT_SECRET_KEY}
isHttpsEnabled: true
server:
  port: 8080
  ssl:
    enabled: ${isHttpsEnabled}
    certificate: classpath:${certificate}
    certificate-private-key: classpath:${certificate-private-key}

frontend: ${frontend}
